"""schema iniziale

Revision ID: 4157f2d26b37
Revises: 
Create Date: 2026-09-15 10:06:08.691634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4157f2d26b37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costanti_disco_tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('diametro_disco_testa', sa.Float(), nullable=True),
    sa.Column('fascia_stampa_utilizzata', sa.Float(), nullable=True),
    sa.Column('passo', sa.Float(), nullable=True),
    sa.Column('sfrido_rifile_percento', sa.Float(), nullable=True),
    sa.Column('sfrido_lunghezza_percento', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costanti_disco_tipo_tipo'), 'costanti_disco_tipo', ['tipo'], unique=True)
    op.create_table('costanti_tipo_capsula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('altezza_testa_ht', sa.Float(), nullable=True),
    sa.Column('sormonto_base_b', sa.Float(), nullable=True),
    sa.Column('rifila_s', sa.Float(), nullable=True),
    sa.Column('sormonto_disco_manuale', sa.Float(), nullable=True),
    sa.Column('sormonto_disco_costante', sa.Float(), nullable=True),
    sa.Column('sfrido_parete_convex_d', sa.Float(), nullable=True),
    sa.Column('sfrido_su_lunghezza_percento', sa.Float(), nullable=True),
    sa.Column('larghezza_fascia_da_dividere', sa.Float(), nullable=True),
    sa.Column('ha_linguetta', sa.Boolean(), nullable=False),
    sa.Column('peso_linguetta_g', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costanti_tipo_capsula_tipo'), 'costanti_tipo_capsula', ['tipo'], unique=True)
    op.create_table('fasce_disponibili',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('larghezza_mm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fasce_disponibili_tipo'), 'fasce_disponibili', ['tipo'], unique=False)
    op.create_table('formati_mandrino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gruppo', sa.String(length=5), nullable=False),
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('diametro_testa', sa.Float(), nullable=True),
    sa.Column('conicita', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formati_mandrino_codice'), 'formati_mandrino', ['codice'], unique=True)
    op.create_table('materiali_disco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('massa_per_superficie', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiali_disco_nome'), 'materiali_disco', ['nome'], unique=True)
    op.create_table('materiali_parete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codice_commerciale', sa.String(length=20), nullable=False),
    sa.Column('spessore_my', sa.Float(), nullable=True),
    sa.Column('peso_specifico', sa.Float(), nullable=True),
    sa.Column('massa_per_superficie', sa.Float(), nullable=True),
    sa.Column('prezzo_e_kg', sa.Float(), nullable=True),
    sa.Column('fascia_fissa_mm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiali_parete_nome'), 'materiali_parete', ['nome'], unique=True)
    op.create_table('varianti_colore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('gruppo', sa.String(length=20), nullable=False),
    sa.Column('densita_g_m2', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_varianti_colore_nome'), 'varianti_colore', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_varianti_colore_nome'), table_name='varianti_colore')
    op.drop_table('varianti_colore')
    op.drop_index(op.f('ix_materiali_parete_nome'), table_name='materiali_parete')
    op.drop_table('materiali_parete')
    op.drop_index(op.f('ix_materiali_disco_nome'), table_name='materiali_disco')
    op.drop_table('materiali_disco')
    op.drop_index(op.f('ix_formati_mandrino_codice'), table_name='formati_mandrino')
    op.drop_table('formati_mandrino')
    op.drop_index(op.f('ix_fasce_disponibili_tipo'), table_name='fasce_disponibili')
    op.drop_table('fasce_disponibili')
    op.drop_index(op.f('ix_costanti_tipo_capsula_tipo'), table_name='costanti_tipo_capsula')
    op.drop_table('costanti_tipo_capsula')
    op.drop_index(op.f('ix_costanti_disco_tipo_tipo'), table_name='costanti_disco_tipo')
    op.drop_table('costanti_disco_tipo')
    # ### end Alembic commands ###
